# Generated by Django 3.1 on 2020-12-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_pwd',
            field=models.TextField(default='none'),
        ),
    ]
