# Generated by Django 3.1 on 2020-12-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_banner_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_pwd',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
