# Generated by Django 3.1 on 2020-12-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_banner_pwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='banner_pwd',
            new_name='Banner_Password',
        ),
    ]
